services:
  postgres:
    image: postgres:18-alpine

    container_name: devhub-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    networks:
      - devhub

  redis:
    image: redis:8.2.9-alpine
    container_name: devhub-redis
    restart: unless-stopped
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - devhub

  mongodb:
    image: mongo:8.0
    container_name: devhub-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - devhub

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.22
    container_name: devhub-elasticsearch
    restart: unless-stopped
    environment:
      discovery.type: single-node

      # 目前仅用于本地开发。
      # 后面部署服务器时必须开启安全认证。
      xpack.security.enabled: "false"

      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - devhub

  rabbitmq:
    image: rabbitmq:4-management
    container_name: devhub-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - devhub

  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile

    image: devhub/minio:local

    container_name: devhub-minio

    restart: unless-stopped

    command:
      - server
      - /data
      - --console-address
      - ":9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

    networks:
      - devhub

  mailpit:
    image: axllent/mailpit:v1.27.4
    container_name: devhub-mailpit
    restart: unless-stopped
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    networks:
      - devhub

networks:
  devhub:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  mongodb_data:
  elasticsearch_data:
  rabbitmq_data:
  minio_data:
