-- +goose Up

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       username VARCHAR(32) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,

                       role SMALLINT NOT NULL DEFAULT 2,
                       status SMALLINT NOT NULL DEFAULT 1,

                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT uq_users_username UNIQUE (username),
                       CONSTRAINT uq_users_email UNIQUE (email),

                       CONSTRAINT ck_users_role
                           CHECK (role IN (1, 2)),

                       CONSTRAINT ck_users_status
                           CHECK (status IN (1, 2))
);


-- +goose Down

DROP TABLE IF EXISTS users;