-- +goose Up
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(160) NOT NULL UNIQUE,
  name VARCHAR(240) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  cover_url TEXT NOT NULL DEFAULT '',
  price_cents BIGINT NOT NULL CHECK (price_cents >= 0),
  stock INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
  status VARCHAR(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_products_public ON products (created_at DESC, id DESC) WHERE status = 'published';

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no VARCHAR(32) NOT NULL UNIQUE,
  product_id BIGINT NOT NULL REFERENCES products(id),
  email VARCHAR(255) NOT NULL,
  quantity INT NOT NULL CHECK (quantity BETWEEN 1 AND 10),
  total_cents BIGINT NOT NULL CHECK (total_cents >= 0),
  status VARCHAR(24) NOT NULL DEFAULT 'pending_payment' CHECK (status IN ('pending_payment', 'paid', 'delivered', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_orders_status_created ON orders (status, created_at DESC);

-- +goose Down
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
