-- +goose Up
ALTER TABLE users DROP CONSTRAINT ck_users_role;
ALTER TABLE users ADD CONSTRAINT ck_users_role CHECK (role IN (1, 2, 3));

CREATE TABLE author_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason VARCHAR(1000) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_author_applications_pending_user ON author_applications(user_id) WHERE status = 'pending';
CREATE INDEX idx_author_applications_review ON author_applications(status, created_at, id);

ALTER TABLE articles ADD COLUMN author_id BIGINT REFERENCES users(id) ON DELETE SET NULL;
UPDATE articles SET author_id = (SELECT id FROM users WHERE role = 1 ORDER BY id LIMIT 1);
CREATE INDEX idx_articles_author ON articles(author_id, created_at DESC, id DESC);

-- +goose Down
ALTER TABLE articles DROP COLUMN author_id;
DROP TABLE author_applications;
UPDATE users SET role = 2 WHERE role = 3;
ALTER TABLE users DROP CONSTRAINT ck_users_role;
ALTER TABLE users ADD CONSTRAINT ck_users_role CHECK (role IN (1, 2));
