-- +goose Up
CREATE TABLE article_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body VARCHAR(2000) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ
);
CREATE INDEX idx_comments_public ON article_comments (article_id, created_at DESC, id DESC)
  WHERE status = 'approved';
CREATE INDEX idx_comments_review ON article_comments (created_at ASC, id ASC)
  WHERE status = 'pending';
CREATE INDEX idx_comments_user_recent ON article_comments (user_id, created_at DESC);

CREATE TABLE link_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  url TEXT NOT NULL,
  avatar_url TEXT NOT NULL DEFAULT '',
  description VARCHAR(280) NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ
);
CREATE INDEX idx_link_applications_review ON link_applications (created_at ASC, id ASC)
  WHERE status = 'pending';
CREATE UNIQUE INDEX uq_link_applications_pending_user ON link_applications (user_id)
  WHERE status = 'pending';

-- +goose Down
DROP TABLE IF EXISTS link_applications;
DROP TABLE IF EXISTS article_comments;
