-- +goose Up
CREATE TABLE gallery_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  location VARCHAR(120) NOT NULL DEFAULT '',
  object_key TEXT NOT NULL DEFAULT '',
  status VARCHAR(16) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  taken_at DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_gallery_public ON gallery_items (created_at DESC, id DESC)
  WHERE status = 'published' AND object_key <> '';

-- +goose Down
DROP TABLE IF EXISTS gallery_items;
