-- +goose Up
CREATE TABLE project_runtime_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  action VARCHAR(8) NOT NULL CHECK (action IN ('start', 'stop')),
  status VARCHAR(12) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'succeeded', 'failed')),
  error_text TEXT NOT NULL DEFAULT '',
  requested_by BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX idx_project_runtime_jobs_active ON project_runtime_jobs(project_id) WHERE status IN ('queued', 'running');
CREATE INDEX idx_project_runtime_jobs_queue ON project_runtime_jobs(status, created_at, id);

-- +goose Down
DROP TABLE IF EXISTS project_runtime_jobs;
